/**
 * Generated by orval v6.26.0 🍺
 * Do not edit manually.
 * Swagger Petstore
 * OpenAPI spec version: 1.0.0
 */
import * as axios from 'axios';
import type {
  AxiosRequestConfig,
  AxiosResponse
} from 'axios'
import type {
  CreatePetsBody
} from '../petstore.schemas'



  /**
 * @summary Create a pet
 */
export const createPets = <TData = AxiosResponse<void>>(
    createPetsBody: CreatePetsBody, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.post(
      `/pets`,
      createPetsBody,options
    );
  }
export type CreatePetsResult = AxiosResponse<void>
