/**
 * Generated by orval v6.26.0 🍺
 * Do not edit manually.
 * Swagger Petstore
 * OpenAPI spec version: 1.0.0
 */
import * as axios from 'axios';
import type {
  AxiosRequestConfig,
  AxiosResponse
} from 'axios'
import type {
  CreatePetsBody,
  ListPetsParams,
  Pet,
  Pets
} from './petstore.schemas'



  /**
 * @summary List all pets
 */
export const listPets = <TData = AxiosResponse<Pets>>(
    params?: ListPetsParams, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.get(
      `/pets`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }

/**
 * @summary Create a pet
 */
export const createPets = <TData = AxiosResponse<void>>(
    createPetsBody: CreatePetsBody, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.post(
      `/pets`,
      createPetsBody,options
    );
  }

/**
 * @summary Info for a specific pet
 */
export const showPetById = <TData = AxiosResponse<Pet>>(
    petId: string, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.get(
      `/pets/${petId}`,options
    );
  }

export type ListPetsResult = AxiosResponse<Pets>
export type CreatePetsResult = AxiosResponse<void>
export type ShowPetByIdResult = AxiosResponse<Pet>
