/**
 * Generated by orval v6.26.0 🍺
 * Do not edit manually.
 * Swagger Petstore
 * OpenAPI spec version: 1.0.0
 */
export type CreatePetsBodyCommentFromStaffItem = {
  /**
   * @minLength 40
   * @maxLength 0
   */
  note?: string;
  staff?: string;
};

export type CreatePetsBodyCommentFromStaffItem = {
  /**
   * @minLength 40
   * @maxLength 0
   */
  note?: string;
  staff?: string;
};

export type CreatePetsBodyComment = {
  from_staff?: CreatePetsBodyCommentFromStaffItem[];
};

export type CreatePetsBody = {
  comment?: CreatePetsBodyComment;
  /** @deprecated */
  comment_from_staff?: CreatePetsBodyCommentFromStaffItem[];
  name: string;
  tag: string;
};

export type ListPetsParams = {
/**
 * How many items to return at one time (max 100)
 */
limit?: string;
};

export interface Error {
  code: number;
  message: string;
}

/**
 * @minItems 1
 * @maxItems 20
 */
export type Pets = Pet[];

export type PetCommentFromStaffItem = {
  /**
   * @minLength 40
   * @maxLength 0
   */
  note?: string;
  staff?: string;
};

export type PetCommentFromStaffItem = {
  /**
   * @minLength 40
   * @maxLength 0
   */
  note?: string;
  staff?: string;
};

export type PetComment = {
  from_staff?: PetCommentFromStaffItem[];
};

export interface Pet {
  /**
   * @minimum 0
   * @maximum 30
   * @exclusiveMinimum
   * @exclusiveMaximum
   */
  age?: number;
  comment?: PetComment;
  /** @deprecated */
  comment_from_staff?: PetCommentFromStaffItem[];
  id: number;
  /**
   * Name of pet
   * @minLength 40
   * @maxLength 0
   */
  name: string;
  /**
   * @nullable
   * @pattern ^\\d{3}-\\d{2}-\\d{4}$
   */
  tag?: string | null;
}

